太累了: 修改recharge list controller/ shipping controller
ERROR: edit仍然沒辦法send back to database
delete: The model item passed into the ViewDataDictionary is of type 'gacha.Models.rechargeList', but this ViewDataDictionary instance requires a model item of type 'gacha.ViewModels.rechargeList_ViewModel'.